#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25
#  in conjunction with Tcl version 8.6
#    Aug 24, 2019 07:48:43 PM IST  platform: Linux

import sys
from create_db import add_new_entry
from create_db import fetch_db

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import create_new_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    create_new_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    create_new_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+650+150")
        top.title("New Toplevel")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.417, rely=0.844, height=51, width=94)
        self.Button1.configure(text='''Submit''',command=self.submit)
        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.60, rely=0.844, height=51, width=94)
        self.Button2.configure(text='''Show Content''',command=fetch_db)

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.483, rely=0.111,height=33, relwidth=0.443)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.483, rely=0.244,height=33, relwidth=0.077)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.483, rely=0.378,height=33, relwidth=0.41)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkFixedFont")

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.217, rely=0.133, relheight=0.056
                , relwidth=0.187)
        self.Message1.configure(text='''Name:-''')
        self.Message1.configure(width=112)

        self.Message2 = tk.Message(top)
        self.Message2.place(relx=0.25, rely=0.244, relheight=0.056
                , relwidth=0.117)
        self.Message2.configure(text='''Gender:-''')
        self.Message2.configure(width=70)

        self.Message3 = tk.Message(top)
        self.Message3.place(relx=0.283, rely=0.378, relheight=0.056
                , relwidth=0.085)
        self.Message3.configure(text='''Post:-''')
        self.Message3.configure(width=70)
    def submit(self):
        x=self.Entry1.get()
        y=self.Entry2.get()
        z=self.Entry3.get()
        add_new_entry.add_points(x,y,z,add_new_entry)

if __name__ == '__main__':
    vp_start_gui()





